import fs from "node:fs/promises";
import path from "node:path";
import { MEMORY_REPORT_PATH } from "./paths.js";
import type { GeneratedFile } from "../types.js";

const memoryFiles = [
  "threadroot/current-focus.md",
  "threadroot/handoff.md",
  "threadroot/decisions.md",
  "threadroot/pitfalls.md",
  "threadroot/sources.md",
];

export type MemoryFinding = {
  path: string;
  level: "ok" | "warning";
  message: string;
  lines: number;
};

export type MemoryReport = {
  version: 1;
  generatedAt: string;
  archiveSuggestion: string;
  findings: MemoryFinding[];
};

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function link(file: string): string {
  return `[${file}](../${file})`;
}

async function inspectMemoryFile(repoRoot: string, relativePath: string): Promise<MemoryFinding> {
  try {
    const content = await fs.readFile(path.join(repoRoot, relativePath), "utf8");
    const lines = content.split("\n").length;
    const hasPlaceholder = /No .* recorded yet|Define the next concrete milestone|has not imported existing project sources/i.test(content);

    if (lines > 120) {
      return {
        path: relativePath,
        level: "warning",
        lines,
        message: "Large memory file. Consider condensing durable facts and archiving session detail.",
      };
    }

    if (hasPlaceholder) {
      return {
        path: relativePath,
        level: "warning",
        lines,
        message: "Still contains starter placeholder content. Update when the project has real durable context.",
      };
    }

    return {
      path: relativePath,
      level: "ok",
      lines,
      message: "Looks concise.",
    };
  } catch {
    return {
      path: relativePath,
      level: "warning",
      lines: 0,
      message: "Missing memory file.",
    };
  }
}

export async function buildMemoryReport(repoRoot: string): Promise<MemoryReport> {
  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    archiveSuggestion: `threadroot/archive/memory-${today()}.md`,
    findings: await Promise.all(memoryFiles.map((file) => inspectMemoryFile(repoRoot, file))),
  };
}

export function memoryReportMarkdown(report: MemoryReport): string {
  const findings = report.findings
    .map((finding) => `- ${finding.level === "ok" ? "OK" : "WARN"} ${link(finding.path)} (${finding.lines} lines): ${finding.message}`)
    .join("\n");

  return `# Memory Review

Generated by \`threadroot refresh --memory\`.

## Findings

${findings}

## Archive Recommendation

If a memory file contains stale session detail, move the stale material into:

- \`${report.archiveSuggestion}\`

Do not delete durable decisions, pitfalls, commands, or source references. Keep the top-level memory files short, current, and useful for new sessions.

## Agent Maintenance Flow

1. Read [handoff](./handoff.md), [current focus](./current-focus.md), [decisions](./decisions.md), and [pitfalls](./pitfalls.md).
2. Keep durable facts in place.
3. Move stale session detail into the archive file above.
4. Run \`threadroot doctor\` and \`threadroot map refresh\` after meaningful structure changes.
`;
}

export function memoryReportFiles(report: MemoryReport): GeneratedFile[] {
  return [
    {
      path: "threadroot/memory-review.md",
      content: memoryReportMarkdown(report),
      generated: false,
    },
    {
      path: MEMORY_REPORT_PATH,
      content: `${JSON.stringify(report, null, 2)}\n`,
      generated: false,
    },
  ];
}
