import type { RepoMap } from "../../types.js";

function link(path: string): string {
  return `[${path}](../${path})`;
}

export function repoMapPlaceholder(): string {
  return `# Repo Map

Run \`threadroot map refresh\` after the project has source files to generate a compact codebase map.

Agents should use this file as an orientation layer, not as a replacement for reading task-relevant source files.
`;
}

export function repoMapMarkdown(map: RepoMap): string {
  const entries = map.entries
    .slice(0, 40)
    .map((entry) => `- ${link(entry.path)} - ${entry.role}`)
    .join("\n");
  const commands = map.commands.map((command) => `- \`${command.command}\` - ${command.purpose}`).join("\n");

  return `# Repo Map

Generated by \`threadroot map refresh\`.

## Project Shape

- Likely profile: ${map.likelyProfile}
- Indexed entries: ${map.entries.length}

## Important Areas

${entries || "- No important areas detected yet."}

## Detected Commands

${commands || "- No commands detected yet."}
`;
}
