import type { ProjectIntent, ProjectProfile, Strictness } from "../../types.js";

export const generatedMarker = "<!-- Generated by threadroot. Edit files in threadroot/ for durable context. -->";

export function strictnessGuidance(strictness: Strictness): string {
  if (strictness === "light") {
    return "Keep guidance lightweight. Prefer quick iteration and update context only when it prevents repeat mistakes.";
  }
  if (strictness === "strict") {
    return "Use a rigorous workflow. Plan before broad edits, validate every change, and record important decisions promptly.";
  }
  return "Use a practical workflow. Keep changes focused, validate meaningful work, and update context when project behavior changes.";
}

export function intentGuidance(intent: ProjectIntent): string {
  const guidance: Record<ProjectIntent, string> = {
    portfolio: "Optimize for clarity, demo quality, readable tradeoffs, and a reviewer-friendly project story.",
    "startup-prototype": "Optimize for fast learning, explicit assumptions, product decisions, and avoiding premature complexity.",
    "saas-app": "Optimize for maintainable product flows, validation, auth/data boundaries, and incremental delivery.",
    "cli-tool": "Optimize for command UX, safe file operations, testable core logic, and clear examples.",
    "api-service": "Optimize for explicit contracts, validation, thin transport handlers, and observable failure modes.",
    "data-project": "Optimize for lineage, model grain, validation, freshness, and documented assumptions.",
    custom: "Optimize for clear repo-owned context and practical agent handoffs.",
  };

  return guidance[intent];
}

export function commandList(profile: ProjectProfile): string {
  return profile.commands.map((item) => `- \`${item.command}\` - ${item.purpose}`).join("\n");
}

export function notesList(profile: ProjectProfile): string {
  return profile.notes.map((note) => `- ${note}`).join("\n");
}
